# Generated by Django 6.0 on 2025-12-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_alter_chamado_status_notificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='chamado',
        ),
    ]
