# Generated by Django 6.0 on 2025-12-29 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_remove_notificacao_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='chamado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='chamados.chamado'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='mensagem',
            field=models.TextField(),
        ),
    ]
