# Generated by Django 6.0 on 2025-12-30 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_respostachamado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicochamado',
            name='lido_por',
            field=models.ManyToManyField(blank=True, related_name='historicos_lidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respostachamado',
            name='lido_por',
            field=models.ManyToManyField(blank=True, related_name='respostas_lidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
