# Generated by Django 6.0 on 2025-12-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_historicochamado_lido_por_respostachamado_lido_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='status',
            field=models.CharField(choices=[('aberto', 'Open'), ('andamento', 'In progress'), ('fechado', 'Closed')], max_length=20),
        ),
    ]
