# Generated by Django 6.0 on 2026-01-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0010_alter_notificacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Média'), ('Alta', 'Alta')], default='Media', max_length=10),
        ),
    ]
