# Generated by Django 6.0 on 2026-01-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_chamado_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
