# Generated by Django 6.0 on 2026-01-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0012_alter_chamado_prioridade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='prioridade',
        ),
        migrations.AddField(
            model_name='chamado',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='chamados_anexos/'),
        ),
    ]
